var toDoList = new Array("wakeup", "running", "yoga")
console.log(toDoList)
toDoList.unshift("cleaning")
toDoList.push("reading")
console.log(toDoList)
toDoList.splice(2,1)
console.log(toDoList)
var pendingtoDoList = new Array("grocery", "meeting")
var new_toDoList = toDoList.concat(pendingtoDoList)
console.log(new_toDoList)